// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8fvZliSD_2jcsTWbAclXSCQxpuSjPFs',
    appId: '1:39295165510:web:69f529bf65f0b9b4aa5647',
    messagingSenderId: '39295165510',
    projectId: 'iot01fb',
    authDomain: 'iot01fb.firebaseapp.com',
    storageBucket: 'iot01fb.firebasestorage.app',
    databaseURL: 'https://iot01fb-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2plfyzct291TKpBw3m6WNECRTmBqPnn4',
    appId: '1:39295165510:android:c53c8f0f85a99113aa5647',
    messagingSenderId: '39295165510',
    projectId: 'iot01fb',
    storageBucket: 'iot01fb.firebasestorage.app',
    databaseURL: 'https://iot01fb-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFBPrGP-AftQf34cwrrIeZDbprOD57bw',
    appId: '1:39295165510:ios:592f830f83155c4baa5647',
    messagingSenderId: '39295165510',
    projectId: 'iot01fb',
    storageBucket: 'iot01fb.firebasestorage.app',
    databaseURL: 'https://iot01fb-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.iot01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTFBPrGP-AftQf34cwrrIeZDbprOD57bw',
    appId: '1:39295165510:ios:592f830f83155c4baa5647',
    messagingSenderId: '39295165510',
    projectId: 'iot01fb',
    storageBucket: 'iot01fb.firebasestorage.app',
    databaseURL: 'https://iot01fb-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.iot01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy8fvZliSD_2jcsTWbAclXSCQxpuSjPFs',
    appId: '1:39295165510:web:a41184557e5534f7aa5647',
    messagingSenderId: '39295165510',
    projectId: 'iot01fb',
    authDomain: 'iot01fb.firebaseapp.com',
    storageBucket: 'iot01fb.firebasestorage.app',
    databaseURL: 'https://iot01fb-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
